- name: Install WinLogbeat
  win_chocolatey:
    name: winlogbeat
    state: present

- name: Create Config Folder
  win_file:
    path: "{{config_dir}}"
    state: directory

- name: Configure WinLogbeat
  win_template:
    src: winlogbeat.yml.j2
    dest: "{{config_dir}}/winlogbeat.yml"
  notify: restart winlogbeat

- name: Start WinLogbeat service
  win_service: 
    name: winlogbeat
    start_mode: auto
    state: started
